update new file of cc-25-group (by Yihui hu)
jtr13/cc20 pull request #55
Opened 2020-11-18 15:29 UTC by YihuiHu-0822

2020-11-18 15:30 UTC, YihuiHu-0822 commented
update cc-25 multivariate grouped data plot to master.

2020-11-25 03:16 UTC, eric0871 commented on multivariate_grouped_data_plot.Rmd
> +## 1 数据准备
Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings.

2020-11-25 03:16 UTC, eric0871 commented on multivariate_grouped_data_plot.Rmd
> +## 2 分类变量分组制图
Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings.

2020-11-25 03:17 UTC, eric0871 commented on multivariate_grouped_data_plot.Rmd
> +### 2.1 筛选特定分组数据及计算频率
Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings.

2020-11-25 03:17 UTC, eric0871 commented on multivariate_grouped_data_plot.Rmd
> +### 2.2 分组频率柱状图
Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings.

2020-11-25 03:17 UTC, eric0871 commented on multivariate_grouped_data_plot.Rmd
> +### 2.3 加入数据标签（并列柱状图）
Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings.

2020-11-25 03:17 UTC, eric0871 commented on multivariate_grouped_data_plot.Rmd
> +### 2.4 加入数据标签（堆积柱状图）
Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings.

2020-11-25 03:17 UTC, eric0871 commented on multivariate_grouped_data_plot.Rmd
> +### 2.5 其他类型柱状图
Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings.

2020-11-25 03:17 UTC, eric0871 commented on multivariate_grouped_data_plot.Rmd
> +## 3 连续变量分组制图
Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings.

2020-11-25 03:17 UTC, eric0871 commented on multivariate_grouped_data_plot.Rmd
> +### 3.1 数据格式
Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings.

2020-11-25 03:17 UTC, eric0871 commented on multivariate_grouped_data_plot.Rmd
> +### 3.2 箱型图
Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings.

2020-11-25 03:17 UTC, eric0871 commented on multivariate_grouped_data_plot.Rmd
> +#### 3.2.1 创建基本箱形图
Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings.

2020-11-25 03:17 UTC, eric0871 commented on multivariate_grouped_data_plot.Rmd
> +#### 3.2.2 创建具有多个组的箱形图
Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings.

2020-11-25 03:17 UTC, eric0871 commented on multivariate_grouped_data_plot.Rmd
> +### 3.3 小提琴图
Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings.

2020-11-25 03:17 UTC, eric0871 commented on multivariate_grouped_data_plot.Rmd
> +#### 3.3.1 使用摘要统计信息创建基本的小提琴图
Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings.

2020-11-25 03:17 UTC, eric0871 commented on multivariate_grouped_data_plot.Rmd
> +#### 3.3.2 创建具有多个组的小提琴图
Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings.

2020-11-25 03:17 UTC, eric0871 commented on multivariate_grouped_data_plot.Rmd
> +### 3.4 点图
Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings.

2020-11-25 03:17 UTC, eric0871 commented on multivariate_grouped_data_plot.Rmd
> +#### 3.4.1 创建基本点图
Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings.

2020-11-25 03:17 UTC, eric0871 commented on multivariate_grouped_data_plot.Rmd
> +#### 3.4.2 创建具有多个组的点图
Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings.

2020-11-25 03:17 UTC, eric0871 commented on multivariate_grouped_data_plot.Rmd
> +### 3.5 带状图
Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings.

2020-11-25 03:18 UTC, eric0871 commented on multivariate_grouped_data_plot.Rmd
> +#### 3.5.1 创建一个基本的带状图
Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings.

2020-11-25 03:18 UTC, eric0871 commented on multivariate_grouped_data_plot.Rmd
> +#### 3.5.2 创建具有多个组的带状图。
Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings.

2020-11-25 03:18 UTC, eric0871 commented on multivariate_grouped_data_plot.Rmd
> +### 3.6 Sina图
Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings.

2020-11-25 03:18 UTC, eric0871 commented on multivariate_grouped_data_plot.Rmd
> +### 3.7 带有误差线的均值和中位数图
Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings.

2020-11-25 03:18 UTC, eric0871 commented on multivariate_grouped_data_plot.Rmd
> +#### 3.7.1 基本均值/中位数图
Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings.

2020-11-25 03:18 UTC, eric0871 commented on multivariate_grouped_data_plot.Rmd
> +#### 3.7.2 多个组的均值/中位数图。
Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings.

2020-11-25 03:18 UTC, eric0871 commented on multivariate_grouped_data_plot.Rmd
> +## 4 总结
Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings.

2020-11-25 03:18 UTC, eric0871 commented on multivariate_grouped_data_plot.Rmd
> +### 4.1 可视化已分组的连续变量的分布
Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings.

2020-11-25 03:18 UTC, eric0871 commented on multivariate_grouped_data_plot.Rmd
> +### 4.2 创建带有误差线的均值和中位数图
Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings.

2020-11-25 03:18 UTC, eric0871 commented on multivariate_grouped_data_plot.Rmd
> +### 4.3 将误差线与小提琴图，点图，线形图和条形图结合起来
Hashtag headers should not be followed by numbers since the hashtags will create numbered subheadings.

2020-11-25 03:19 UTC, eric0871 requested changes
The file needs to make some changes before merging. Please see comments for details.

2020-11-29 12:25 UTC, tracy3057 commented
Thank you for your contribution! 🎉

2020-11-29 12:25 UTC, merged